---
common:

appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.travis.yml:
  delete: true
Rakefile:
  changelog_user: "puppetlabs"
  extra_disabled_lint_checks:
   - unquoted_string_in_case
   - manifest_whitespace_opening_brace_before
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      version: '= 1.15.2'
    - gem: 'octokit'
      version:
       '= 4.21.0'
